"""Harmonic phonons by finite displacements (phonopy) and the heat capacity C_V.

Each symmetry-distinct atom of a supercell is displaced by a small distance, the forces on all
atoms of every displaced supercell give the force constants, and the phonon frequencies on a
q-point mesh give the thermal properties in the harmonic approximation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

import numpy as np
from ase import Atoms
from phonopy import Phonopy
from pymatgen.io.phonopy import get_phonopy_structure

if TYPE_CHECKING:
    from collections.abc import Sequence

    from pymatgen.core import Structure


def make_phonopy(structure: Structure, *, min_supercell_length: float = 15.0, symprec: float = 1e-5) -> Phonopy:
    """Set up phonopy for a relaxed primitive cell.

    The supercell repeats the cell ``ceil(min_supercell_length / |a_i|)`` times along each lattice
    vector a_i (upstream matcalc's rule, with 20 Å; it uses vector lengths, not the distance between
    faces).

    Args:
        structure: Relaxed primitive cell.
        min_supercell_length: Minimum length of each supercell vector (Å).
        symprec: Symmetry tolerance for spglib (Å).

    Returns:
        A ``Phonopy`` object without displacements yet.
    """
    repeats = np.ceil(min_supercell_length / np.array(structure.lattice.abc)).astype(int)
    return Phonopy(
        get_phonopy_structure(structure),
        supercell_matrix=np.diag(repeats),
        symprec=symprec,
        primitive_matrix="P",
    )


def displaced_supercells(phonon: Phonopy, *, displacement: float = 0.015) -> list[Atoms]:
    """Generate the displaced supercells whose forces give the force constants.

    Args:
        phonon: Phonopy object from ``make_phonopy``.
        displacement: Displacement of the moved atom (Å).

    Returns:
        One ASE ``Atoms`` per displaced supercell, in phonopy's order.
    """
    phonon.generate_displacements(distance=displacement)
    # The same cells as phonopy's ``supercells_with_displacements``, built directly from the perfect
    # supercell (about twice as fast).
    supercell = phonon.supercell
    cells = []
    for entry in phonon.dataset["first_atoms"]:
        if not entry.get("included", True):
            continue
        positions = supercell.positions.copy()
        positions[entry["number"]] += entry["displacement"]
        cells.append(Atoms(numbers=supercell.numbers, cell=supercell.cell, positions=positions, pbc=True))
    return cells


@dataclass
class ThermalProperties:
    """Harmonic thermal properties on a temperature grid (per mole of the primitive cell).

    Attributes:
        temperatures: Temperatures (K).
        heat_capacity: Constant-volume heat capacity C_V (J/(K·mol)).
        entropy: Vibrational entropy (J/(K·mol)).
        free_energy: Vibrational Helmholtz free energy (kJ/mol).
        min_frequency: Lowest phonon frequency on the mesh (THz); negative values are imaginary
            modes, a sign that the structure is dynamically unstable with this potential.
    """

    temperatures: np.ndarray
    heat_capacity: np.ndarray
    entropy: np.ndarray
    free_energy: np.ndarray
    min_frequency: float

    def heat_capacity_at(self, temperature: float) -> float:
        """C_V at one temperature of the grid.

        Args:
            temperature: Temperature (K); must be one of ``temperatures``.

        Returns:
            C_V at that temperature (J/(K·mol)).

        Raises:
            ValueError: If ``temperature`` is not on the grid.
        """
        matches = np.flatnonzero(np.isclose(self.temperatures, temperature))
        if matches.size == 0:
            raise ValueError(f"{temperature} K is not on the temperature grid")
        return float(self.heat_capacity[matches[0]])


def thermal_properties(
    phonon: Phonopy,
    forces: Sequence[np.ndarray],
    *,
    t_min: float = 0,
    t_max: float = 1000,
    t_step: float = 10,
) -> ThermalProperties:
    """Force constants → phonon frequencies on a mesh → harmonic thermal properties.

    Only the compact force constants (rows of the atoms in the primitive cell) are built, and no
    eigenvectors are kept; both give the same frequencies as the full arrays while needing far less
    memory for large supercells.

    Args:
        phonon: Phonopy object whose displacements were generated by ``displaced_supercells``.
        forces: Forces on every atom of every displaced supercell (eV/Å), same order.
        t_min: Lowest temperature of the grid (K).
        t_max: Highest temperature of the grid (K).
        t_step: Temperature step (K).

    Returns:
        The thermal properties.
    """
    phonon.forces = forces
    phonon.produce_force_constants(calculate_full_force_constants=False)
    phonon.run_mesh(with_eigenvectors=False)
    min_frequency = float(np.min(phonon.mesh.frequencies))
    phonon.run_thermal_properties(t_step=t_step, t_max=t_max, t_min=t_min)
    thermal = phonon.thermal_properties
    return ThermalProperties(
        temperatures=np.asarray(thermal.temperatures),
        heat_capacity=np.asarray(thermal.heat_capacity),
        entropy=np.asarray(thermal.entropy),
        free_energy=np.asarray(thermal.free_energy),
        min_frequency=min_frequency,
    )
